### PR TITLE
Refactored code so IBOutlets show on Xcode 6's Interface Builder

### PR DESCRIPTION
**Pull request by rsanchezsaez**
The

```
#if TARGET_OS_IPHONE
#else
#endif
```

macros (which provide universal iOS/OS X support) were causing some problems and Xcode 6 was not showing the IBOutlets. I refactored the code and now is Xcode 6 friendly.

Tested and working both on iOS and OS X.

### CODE REVIEW

**Comment by depth42** [comment]
Hi Ricardo, thanks for your patches. Sadly, both the iOS and MacOS demo projects do not compile. They still contain references to source files which you deleted in your changes. Can you fix this? Cheers, Frank

**Comment by rsanchezsaez** [comment]
I just fixed both sample projects. Cheers.

**Comment by rsanchezsaez** [comment]
By the way, this also includes @booiiing pull request (fix for new swizzle method signature).

**Comment by bobspryn** [comment]
:+1:

**Comment by rsanchezsaez** [comment]
I realized that, sadly, my refactor is not enough to make Xcode &.x comply with it. The IBOUTLET shows on Xcode, but it isn't assignable by ctrl-dragging a view or constraint to it.

It seems that having 

```
#if TARGET_OS_IPHONE
#else
#endif
```

constructs around screws with it not matter what.

The only effective solution that worked for us on Xcode 6.x was to completely remove the OS X support. That makes it all behave fine.

**Comment by bobspryn** [comment]
@rsanchezsaez I pulled OS X support and still not working. Do you have your version posted?

**Comment by rsanchezsaez** [comment]
I have added an [iOS only branch](https://github.com/obviousengineering/AutolayoutExtensions/tree/ios) to my fork. It shows the `IBOutlets` for me, try it out.

**Pull request closed without merging**
